import getpass
import telnetlib


HOST = "192.168.100.205"
user = input("Enter your telnet username: ")
password = getpass.getpass()

tn = telnetlib.Telnet(HOST)

tn.read_until(b"Username: ")
tn.write(user.encode('ascii') + b"\n")

if password:
    tn.read_until(b"Password: ")
    tn.write(password.encode('ascii') + b"\n")

loc = str(input(" enter the location file : \n"))
fname=str(input(" enter the  file name : \n"))
ftp_ip=str(input(" enter server ftp ip "))
ft= str("ccopy "+ loc +fname+ " "+ "ftp:"+ "\n"+ ftp_ip + "\n" + fname + "\n")
tn.write(b" enable  \n")
tn.write(b"dir all \n")
tn.write(b"sshow version \n")
tn.write(bytes(ft.encode('ascii') + b"\n"))
op=("Address or name of remote host []?")

tn.write(b"\n")
tn.write(b"exit\n")
print(tn.read_all().decode('ascii'))

